### ISSUE TITLE
Reproduction Failure: High Loss Throughout Training

### ISSUE THREAD

**Issue by helloworld751** [jiangxinke/ASD-VAE#1]
Hi there,

I'm impressed by your excellent work. However, I am unable to reproduce the performance reported in your paper using your source code. The loss remains high throughout the training phase, resulting in extremely low accuracy. Could you provide any insights or guidance on this issue?

Thank you in advance.

My Colab notebook for reproduction is attached: https://colab.research.google.com/drive/1O5iAqSefg09TaexTA5XHFGSykeEU8KbM?usp=sharing

**Comment by ASD-VAE-Anonymous** [comment]
This issue was solved in https://github.com/ASD-VAE-Anonymous/ASD-VAE/issues. So i decide to close this issue.
