### ISSUE TITLE
discriminator

### ISSUE THREAD

**Issue by cyang810** [jiangxinke/ASD-VAE#2]
Thank you for your excellent work, I see that the paper only mentions Attribute completion loss(reconstruction loss and regularization loss designed for the coupled-and-decoupled learning process) and Prediction loss, but there is a GAN in the code. All the data sets discriminator as True, it seems that this part should be used, can you give me more details about discriminator?  Thank you very much

**Comment by jiangxinke** [comment]
Hi, I'm impressed by your wise eyes. Actually, we apply a GAN to motivate attribute repairment (which is discussed in Appendix). If you wanna more details about this, please leave your email and I will give this document to you! ~

**Comment by cyang810** [comment]
Thank you for doing such a thorough job. I am honored to learn more about the details of this excellent paper. My email is cyang810@163.com. Best regards!

**Comment by Zwyoooo** [comment]
Hello, could you send me the appendix as well？Thank you very much. 1287845980@qq.com
